# Use a Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and lock file
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's code
COPY . .

# Expose the Vite port
EXPOSE 5173

# Run the Vite dev server
CMD ["npm", "run", "dev"]
