import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        welcome: 'Welcome to TradeSense AI',
        hero_title: 'The First AI-Powered Prop Firm for Africa',
        hero_subtitle: 'Join the next generation of trading. Get funded and trade with our capital.',
        start_challenge: 'Start Challenge',
        dashboard: 'Dashboard',
        trading: 'Trading',
        leaderboard: 'Leaderboard',
        pricing: 'Pricing',
        contact: 'Contact us',
        admin: 'Admin',
        login: 'Login',
        register: 'Register',
        nav_dashboard: 'Dashboard',
        nav_trading: 'Trading',
        nav_challenge: 'Challenge',
        nav_leaderboard: 'Leaderboard',
        nav_wallet: 'Wallet',
        nav_profile: 'Profile',
        nav_logout: 'Logout',
        nav_admin: 'Admin',
        theme_light: 'Light',
        theme_dark: 'Dark',
        language: 'Language',
        chat_title: 'TradeSense Assistant',
        chat_subtitle: 'Ask us anything',
        chat_placeholder: 'Type your message...',
        chat_open: 'Open chat',
        chat_close: 'Close chat',
        chat_thinking: 'Typing...',
        chat_error: 'Sorry, something went wrong.',
        dashboard_title: 'Dashboard',
        dashboard_subtitle: 'Welcome back, Trader!',
        dashboard_start_trading: 'Start Trading',
        dashboard_account_balance: 'Account Balance',
        dashboard_equity: 'Equity',
        dashboard_total_profit: 'Total Profit',
        dashboard_daily_drawdown: 'Daily Drawdown',
        dashboard_challenge_progress: 'Challenge Progress',
        dashboard_profit_target_progress: 'Profit Target Progress',
        dashboard_live_hub: 'Live Hub - Africa & Global',
        dashboard_ai_banner: 'AI Assistant just published fresh signals',
        dashboard_ai_signals: 'AI Assistant Trade Signals',
        dashboard_ai_loading: 'Analyzing markets...',
        dashboard_ai_empty: 'No clear signals detected.',
        dashboard_view_all_signals: 'View All Signals',
        dashboard_confidence: 'Confidence:',
        dashboard_onboarding: 'Onboarding',
        dashboard_onboarding_title: 'Getting started checklist',
        dashboard_onboarding_step_profile: 'Verify account details',
        dashboard_onboarding_step_plan: 'Pick your challenge size',
        dashboard_onboarding_step_trade: 'Place your first trade',
        dashboard_onboarding_cta: 'Complete profile',
        dashboard_checklist_title: 'Progress checklist',
        dashboard_checklist_hint: 'Complete these steps to unlock funding and live market access.',
        dashboard_checklist_profile: 'Verify profile & documents',
        dashboard_checklist_challenge: 'Choose your challenge size',
        dashboard_checklist_trade: 'Place your first live trade',
        dashboard_checklist_status_completed: 'Completed',
        dashboard_checklist_status_pending: 'Pending',
        dashboard_reco_title: 'Recommendations',
        dashboard_reco_subtitle: 'Next best actions for your account',
        dashboard_reco_hint: 'Updated now',
        dashboard_reco_funded_title: 'Unlock funded features',
        dashboard_reco_funded_desc: 'Upgrade to access live data, withdrawals, and AI signals.',
        dashboard_reco_funded_action: 'Upgrade now',
        dashboard_reco_signals_title: 'AI signals ready',
        dashboard_reco_signals_desc: 'Review the latest opportunities and act fast.',
        dashboard_reco_signals_empty_title: 'No signals yet',
        dashboard_reco_signals_empty_desc: 'Check live markets or refresh later.',
        dashboard_reco_signals_action: 'Open signals',
        dashboard_reco_watchlist_title: 'Curate your watchlist',
        dashboard_reco_watchlist_desc: 'Follow the assets you trade most often.',
        dashboard_reco_watchlist_action: 'Open trading',
        dashboard_reco_rules_title: 'Review challenge rules',
        dashboard_reco_rules_desc: 'Stay within drawdown and time limits.',
        dashboard_reco_rules_action: 'View rules',
        dashboard_news_title: 'Market Headlines',
        dashboard_news_subtitle: 'Latest macro and stock updates',
        dashboard_news_hint: 'Live feed',
        dashboard_news_empty: 'No headlines available.',
        dashboard_news_source: 'Source:',
        dashboard_market_pulse: 'Market Pulse',
        dashboard_market_pulse_subtitle: 'Trend snapshots linked to live pricing',
        dashboard_market_pulse_window: 'Last 28 sessions',
        dashboard_market_no_chart: 'No chart data yet',
        dashboard_market_trend: '28D trend',
        funded_only_title: 'Funded only',
        funded_only_desc: 'Upgrade to a funded account to access live market data.',
        funded_only_ai: 'AI signals are available for funded accounts only.',
        funded_only_charts: 'TradingView charts are available for funded accounts only.',
        funded_only_live_data: 'Live market data is available for funded accounts only.',
        funded_only_badge: 'Funded only',
        profile_title: 'Profile Settings',
        profile_subtitle: 'Manage your account settings and preferences',
        profile_photo: 'Profile Photo',
        profile_upload_photo: 'Upload Photo',
        profile_remove_photo: 'Remove Photo',
        profile_remove_photo_confirm: 'Remove your profile photo?',
        profile_personal_info: 'Personal Information',
        profile_full_name: 'Full Name',
        profile_email: 'Email Address',
        profile_phone: 'Phone Number',
        profile_country: 'Country',
        profile_save_changes: 'Save Changes',
        profile_change_password: 'Change Password',
        profile_current_password: 'Current Password',
        profile_new_password: 'New Password',
        profile_confirm_password: 'Confirm New Password',
        profile_update_password: 'Update Password',
        profile_preferences: 'Preferences',
        profile_language: 'Language',
        profile_dark_mode: 'Dark Mode',
        profile_dark_mode_desc: 'Use theme across the platform',
        profile_danger_zone: 'Danger Zone',
        profile_delete_account: 'Delete Account',
        profile_delete_warning: 'Once you delete your account, there is no going back. Please be certain.',
        profile_delete_confirm: 'Delete your account permanently? This cannot be undone.',
        wallet_title: 'Portfolio & Wallet',
        wallet_subtitle: 'Track positions, PnL, and payments',
        wallet_balance: 'Balance',
        wallet_equity: 'Equity',
        wallet_open_positions: 'Open Positions',
        wallet_asset: 'Asset',
        wallet_qty: 'Qty',
        wallet_avg_entry: 'Avg Entry',
        wallet_last: 'Last',
        wallet_pnl: 'PnL',
        wallet_action: 'Action',
        wallet_close: 'Close',
        wallet_closing: 'Closing...',
        wallet_no_positions: 'No open positions.',
        wallet_allocation: 'Portfolio Allocation',
        wallet_total: 'Total',
        wallet_allocation_empty: 'No allocation data yet.',
        wallet_trade_history: 'Trade History',
        wallet_trade_empty: 'No trades yet.',
        wallet_side: 'Side',
        wallet_price: 'Price',
        wallet_challenge: 'Challenge',
        wallet_started: 'Started',
        wallet_days_remaining: 'days remaining',
        wallet_upgrade_plan: 'Upgrade Plan',
        wallet_available_plans: 'Available Plans',
        wallet_popular: 'Popular',
        wallet_account: 'account',
        wallet_current_plan_label: 'Current Plan',
        wallet_select_plan: 'Select Plan',
        wallet_payment_history: 'Payment History',
        wallet_export: 'Export',
        wallet_transaction: 'Transaction',
        wallet_date: 'Date',
        wallet_method: 'Method',
        wallet_amount: 'Amount',
        wallet_status: 'Status',
        wallet_payment_empty: 'No payments yet.',
        wallet_complete_payment: 'Complete Payment',
        wallet_payment_desc: 'You will be redirected to PayPal to complete your payment securely.',
        wallet_selected_plan: 'Selected Plan',
        wallet_cancel: 'Cancel',
        wallet_pay_paypal: 'Pay with PayPal',
        wallet_withdraw_title: 'Withdrawals',
        wallet_withdraw_subtitle: 'Request a payout from your funded profit.',
        wallet_withdraw_available: 'Available profit',
        wallet_withdraw_min_profit: 'Minimum profit required',
        wallet_withdraw_status: 'Status',
        wallet_withdraw_status_ready: 'Eligible',
        wallet_withdraw_status_locked: 'Locked',
        wallet_withdraw_amount: 'Withdrawal amount',
        wallet_withdraw_request: 'Request withdrawal',
        wallet_withdraw_processing: 'Processing...',
        wallet_withdraw_not_eligible: 'Withdrawals unlock after reaching profit of',
        wallet_withdraw_requested: 'Withdrawal requested',
        wallet_withdraw_requested_desc: 'Your request has been submitted.',
        challenge_title: 'Challenge Progress',
        trading_title: 'Trading Terminal',
        trading_subtitle: 'African & Global Markets - Real Time',
        trading_watchlist: 'Market Watchlist',
        trading_watchlist_subtitle: 'Search, filter, and track live prices across markets.',
        trading_hide_companies: 'Hide companies',
        trading_show_companies: 'Show companies',
        trading_companies_hidden: 'Companies list hidden.',
        trading_assets: 'Assets',
        trading_live: 'Live',
        trading_search: 'Search symbol or company...',
        trading_sort_price: 'Sort: Price',
        trading_sort_volume: 'Sort: Volume',
        trading_sort_change: 'Sort: % Change',
        trading_sort_desc: 'Desc',
        trading_sort_asc: 'Asc',
        trading_filter_all: 'All',
        trading_filter_gainers: 'Gainers',
        trading_filter_losers: 'Losers',
        trading_filter_volume: 'High Volume',
        trading_execution: 'Trade Execution',
        trading_buy: 'BUY',
        trading_sell: 'SELL',
        trading_quantity: 'Quantity Units',
        trading_quantity_lots: 'Quantity (Lots)',
        trading_quantity_shares: 'Quantity (Shares)',
        trading_market_price: 'Market Price',
        trading_asset_type: 'Asset Type',
        trading_side: 'Side',
        trading_qty: 'Qty',
        trading_qty_lots: 'Lots',
        trading_qty_shares: 'Shares',
        trading_notional: 'Notional',
        trading_est: 'Est. 1%',
        trading_execute: 'Execute',
        trading_ai_hub: 'TradeSense AI Prediction Hub',
        trading_unit_lot: 'lot',
        trading_unit_lots: 'lots',
        trading_unit_shares: 'shares',
        trading_unit_units: 'units',
        trading_unit_coins: 'coins',
        trading_tp_sl: 'Take Profit / Stop Loss',
        trading_take_profit: 'Take Profit',
        trading_stop_loss: 'Stop Loss',
        trading_tp_mode_percent: '% mode',
        trading_tp_mode_price: 'Price mode',
        trading_tp_price: 'TP @',
        trading_sl_price: 'SL @',
        trading_view_mode: 'View mode',
        trading_view_simple: 'Simple',
        trading_view_pro: 'Pro',
        trading_tab_chart: 'Chart',
        trading_tab_trade: 'Trade',
        trading_tab_watchlist: 'Watchlist',
        trading_market_all: 'All',
        trading_market_crypto: 'Crypto',
        trading_market_forex: 'Forex',
        trading_market_nasdaq: 'Nasdaq',
        trading_market_bvc: 'Bourse de Casablanca',
        trading_price: 'Price',
        trading_change: 'Change',
        trading_volume: 'Volume',
        trading_risk: 'RISK',
        trading_risk_tooltip: 'Risk based on drawdown thresholds',
        trading_live_data: 'LIVE DATA',
        trading_rules_notice: '⚠️ By executing, you agree to the Prop Firm rules: 5% Daily Drawdown / 10% Overall.',
        trading_risk_low: 'Low',
        trading_risk_medium: 'Medium',
        trading_risk_high: 'High',
        trading_vol: 'Vol',
        trading_live_news: 'Live News',
        trading_loading_news: 'Loading news...',
        challenge_demo_type: 'Demo Account',
        challenge_trial_type: 'Free Trial',
        challenge_paid_type: 'Pro Challenge',
        challenge_subtitle: 'Track your trading challenge progress',
        challenge_demo_active: 'Demo Mode Active',
        challenge_trial_active: 'Free Trial Mode',
        challenge_demo_desc: 'This is a demo account for practice. You cannot become funded from a demo account.',
        challenge_trial_desc: 'This is a free trial to test challenge rules. Upgrade to a paid challenge to become funded.',
        challenge_upgrade: 'Upgrade to Paid Challenge',
        challenge_starting_balance: 'Starting Balance',
        challenge_current_equity: 'Current Equity',
        challenge_profit_loss: 'Profit/Loss',
        challenge_limit: 'Limit:',
        challenge_approaching_limit: 'Approaching limit',
        challenge_rules_title: 'Trading Rules',
        challenge_status_title: 'Challenge Status Guide',
        challenge_status_active: 'Challenge is in progress. Trade carefully and follow all rules.',
        challenge_status_passed: "Congratulations! You've passed and are ready to be funded.",
        challenge_status_failed: 'Challenge failed due to rule violation. You can start a new challenge.',
        challenge_rule_profit_target: 'Profit Target',
        challenge_rule_none: 'None',
        challenge_rule_profit_desc: 'Reach the profit target to pass',
        challenge_rule_profit_demo: 'No profit requirement for demo',
        challenge_rule_daily_drawdown: 'Daily Drawdown',
        challenge_rule_daily_desc: 'Maximum loss allowed in a single day',
        challenge_rule_total_drawdown: 'Total Drawdown',
        challenge_rule_total_desc: 'Maximum total loss from peak balance',
        challenge_rule_time_remaining: 'Time Remaining',
        challenge_rule_time_desc: 'Complete within the time limit',
        challenge_days: 'days',
        challenge_left: 'left',
        challenge_rule_news: 'No trading during high-impact news (2 mins before/after)',
        challenge_rule_risk: 'Maximum 3% risk per trade',
        challenge_rule_sl: 'Must use stop-loss on all positions',
        challenge_rule_weekend: 'Weekend holding is allowed',
        challenge_rule_days: 'Minimum 5 trading days required',
        challenge_rule_bot: 'No EA/Bot trading without approval',
        hero_badge: 'Africa-first prop firm with BVC access',
        hero_cta_text: 'Start Challenge',
        hero_cta_tagline: 'Funded challenges in 3 steps—finish onboarding, show discipline, trade with our capital.',
        hero_trust_badge: 'BVC-Accredited Prop Firm',
        hero_trust_subtext: 'Live Casablanca data, 24/7 AI monitoring, and trusted by 2,500+ African traders.',
        hero_title_line1: 'Trade Smarter.',
        hero_title_line2: 'Get Funded.',
        hero_subtitle: 'Join the next generation prop trading platform. AI signals, real-time charts, professional tools. Pass the challenge and trade with our capital.',
        hero_view_plans: 'View Plans',
        hero_stat_capital: 'Funded capital',
        hero_stat_traders: 'Active traders',
        hero_stat_success: 'Success rate',
        hero_stat_risk: 'Risk monitoring',
        trust_stat_traders: 'Traders funded',
        trust_stat_payout: 'Avg. payout',
        trust_stat_winrate: 'Weekly winrate',
        trust_stat_markets: 'Markets covered',
        trust_stat_markets_value: 'BVC + Global',
        pillars_label: 'Platform model',
        pillars_title: 'Built on three pillars',
        pillars_subtitle: 'A clear structure that keeps traders focused, compliant, and consistent.',
        pillars_trade_title: 'Trade',
        pillars_trade_desc: 'Multi-asset execution with BVC, FX, crypto, and Nasdaq on one terminal.',
        pillars_risk_title: 'Risk',
        pillars_risk_desc: 'Automated rules, drawdown guardrails, and real-time risk scoring.',
        pillars_learn_title: 'Learn',
        pillars_learn_desc: 'Guided education, AI summaries, and playbooks for every level.',
        bvc_title: 'Local market, global-grade tooling',
        bvc_subtitle: 'Track Moroccan equities in real time with the same execution flow as FX and crypto.',
        bvc_section_title: 'Bourse de Casablanca',
        bvc_cta_primary: 'Explore BVC',
        bvc_cta_secondary: 'See top BVC traders',
        bvc_card_shares: 'Shares trading',
        bvc_card_shares_desc: 'Buy and sell in shares (min 1)',
        bvc_card_tv: 'TradingView charts',
        bvc_card_tv_desc: 'CSEMA symbols and live ticks',
        bvc_card_risk: 'Risk alignment',
        bvc_card_risk_desc: 'Same challenge rules across markets',
        testimonials_title: 'Trusted by Traders',
        testimonials_subtitle: 'Join thousands of disciplined traders building consistent results with TradeSense AI.',
        testimonial_ahmed_role: 'Funded Trader • Casablanca',
        testimonial_ahmed_content: 'Clear rules, fast execution, and reliable risk limits. I passed in 3 weeks and stayed consistent.',
        testimonial_sarah_role: 'Pro Trader • Rabat',
        testimonial_sarah_content: 'The risk dashboard keeps me disciplined. The platform feels professional and focused.',
        testimonial_youssef_role: 'Elite Trader • Marrakech',
        testimonial_youssef_content: 'The BVC watchlist and TradingView charts are a huge plus. Everything is in one terminal.',
        trader_stories_title: 'Trader Stories',
        trader_stories_subtitle: 'Live-funded traders share how TradeSense AI keeps them disciplined and capitalized.',
        story_lina_role: 'Rabat · Funded Trader',
        story_lina_quote: 'Clear rules, dependable funding and AI-ready signals let me stay calm and trade bigger in 3 weeks.',
        story_omar_role: 'Casablanca · Risk Analyst',
        story_omar_quote: 'The risk monitoring feels like a second set of eyes—perfect for staying compliant on every trade.',
        story_samira_role: 'Dubai · Growth Trader',
        story_samira_quote: 'Scaling to a $50k account felt smooth. Their dashboard + live Casablanca feeds keep me ahead.',
        pricing_meta_duration: 'Challenge length',
        pricing_meta_target: 'Profit target',
        pricing_meta_rules: 'Drawdown rules',
        checkout_order_summary: 'Order Summary',
        checkout_payment_options: 'Payment Options',
        checkout_total: 'Total',
        checkout_pay_now: 'Pay now',
        checkout_title: 'Checkout',
        checkout_subtitle: 'Complete your challenge payment',
        checkout_plan_label: 'Plan',
        checkout_account_size_label: 'Account Size',
        checkout_price_label: 'Price',
        checkout_loading: 'Loading challenge...',
        checkout_paypal_label: 'PayPal',
        checkout_paypal_connected: 'Connected',
        checkout_paypal_not_configured: 'Not configured',
        checkout_paypal_loading: 'Loading PayPal...',
        checkout_paypal_missing: 'PayPal not configured in admin',
        checkout_cmi_loading: 'Loading Gateway...',
        checkout_cmi_button: 'Pay with Carte Bancaire (CMI)',
        checkout_crypto_loading: 'Creating Order...',
        checkout_crypto_button: 'Pay with Binance Pay',
        admin_title: 'Admin Control Center',
        admin_subtitle: 'Manage real-time challenges and user status overrides',
        admin_accounts: 'Account Management',
        admin_user_details: 'User Details',
        admin_logs: 'Admin Action Logs',
        admin_paypal_config: 'PayPal Configuration',
        admin_cmi_config: 'CMI Configuration',
        admin_crypto_config: 'Binance Pay Configuration',
        admin_action_logs: 'Admin Action Logs',
        admin_account_management: 'Account Management',
        admin_total_accounts: 'Total Accounts',
        admin_active_challenges: 'Active Challenges',
        admin_funded: 'Funded',
        admin_failed: 'Failed',
        admin_error: 'Error',
        admin_saved: 'Saved',
        admin_config_updated: 'Config updated',
        admin_fetch_accounts_error: 'Failed to fetch accounts',
        admin_fetch_details_error: 'Failed to load account details',
        admin_paypal_save_error: 'Failed to save PayPal config',
        admin_cmi_save_error: 'Failed to save CMI config',
        admin_crypto_save_error: 'Failed to save Crypto config',
        admin_status_updated: 'Status Updated',
        admin_status_updated_desc: 'Account #{id} set to {status}',
        admin_status_update_error: 'Failed to update status',
        admin_search_accounts: 'Search accounts...',
        admin_user: 'User',
        admin_challenge: 'Challenge',
        admin_balance: 'Balance',
        admin_status: 'Status',
        admin_actions: 'Actions',
        admin_fund_user: 'Fund User',
        admin_fail_user: 'Fail User',
        admin_reset_active: 'Reset to Active',
        admin_loading: 'Loading...',
        admin_select_account: 'Select an account to see full user details.',
        admin_quick_actions: 'Quick Actions',
        admin_fund: 'Fund',
        admin_fail: 'Fail',
        admin_reset: 'Reset',
        admin_open_positions: 'Open Positions',
        admin_qty: 'Qty',
        admin_avg: 'Avg',
        admin_no_positions: 'No open positions.',
        admin_recent_trades: 'Recent Trades',
        admin_no_trades: 'No recent trades.',
        admin_equity: 'Equity',
        admin_paypal_client_id: 'Client ID',
        admin_paypal_client_id_placeholder: 'PayPal client id',
        admin_paypal_client_secret: 'Client Secret',
        admin_paypal_client_secret_placeholder: 'PayPal client secret',
        admin_mode: 'Mode',
        admin_currency: 'Currency',
        admin_currency_placeholder: 'USD',
        admin_save_paypal: 'Save PayPal Config',
        admin_cmi_store_id: 'Store ID',
        admin_cmi_store_id_placeholder: 'CMI store id',
        admin_cmi_shared_secret: 'Shared Secret',
        admin_cmi_shared_secret_placeholder: 'CMI shared secret',
        admin_save_cmi: 'Save CMI Config',
        admin_crypto_api_key: 'API Key',
        admin_crypto_api_key_placeholder: 'Binance Pay API key',
        admin_crypto_api_secret: 'API Secret',
        admin_crypto_api_secret_placeholder: 'Binance Pay API secret',
        admin_crypto_merchant_id: 'Merchant ID (optional)',
        admin_crypto_merchant_id_placeholder: 'Merchant ID',
        admin_save_crypto: 'Save Binance Pay Config',
        admin_no_logs: 'No logs yet.',
        admin_payments: 'Payments',
        admin_refresh_data: 'Refresh Data',
        admin_manage_payments: 'Manage Payments',
        admin_manage_accounts: 'Manage Accounts',
        admin_quick_actions_hint: 'Use quick actions to jump into critical admin workflows.',
        admin_recent_logs: 'Recent Logs',
        admin_view_all_logs: 'View All Logs',
        admin_user_profile: 'User Profile',
        admin_user_name: 'Username',
        admin_user_email: 'User Email',
        admin_save_user: 'Save User',
        admin_user_updated: 'User updated',
        admin_user_update_error: 'Failed to update user',
        admin_account_settings: 'Account Settings',
        admin_save_account: 'Save Account',
        admin_account_updated: 'Account updated',
        admin_account_update_error: 'Failed to update account',
        admin_security: 'Security',
        admin_new_password: 'New Password',
        admin_reset_password: 'Reset Password',
        admin_password_reset: 'Password reset',
        admin_password_reset_error: 'Failed to reset password',
        admin_delete_account: 'Delete Account',
        admin_delete_account_confirm: 'Delete this account? This cannot be undone.',
        admin_account_deleted: 'Account deleted',
        admin_account_deleted_desc: 'The account has been removed.',
        admin_account_delete_error: 'Failed to delete account',
        admin_initial_balance: 'Initial Balance',
        admin_daily_starting_equity: 'Daily Starting Equity',
    },
    fr: {
        welcome: 'Bienvenue sur TradeSense AI',
        hero_title: "La Première Prop Firm Assistée par IA pour l'Afrique",
        hero_subtitle: 'Rejoignez la nouvelle génération de trading. Obtenez un financement et tradez avec notre capital.',
        start_challenge: 'Démarrer le Challenge',
        dashboard: 'Tableau de bord',
        trading: 'Trading',
        leaderboard: 'Classement',
        pricing: 'Tarification',
        contact: 'Contact',
        admin: 'Admin',
        login: 'Connexion',
        register: 'Inscription',
        nav_dashboard: 'Tableau de bord',
        nav_trading: 'Trading',
        nav_challenge: 'Challenge',
        nav_leaderboard: 'Classement',
        nav_wallet: 'Portefeuille',
        nav_profile: 'Profil',
        nav_logout: 'Déconnexion',
        nav_admin: 'Admin',
        theme_light: 'Clair',
        theme_dark: 'Sombre',
        language: 'Langue',
        chat_title: 'Assistant TradeSense',
        chat_subtitle: 'Posez vos questions',
        chat_placeholder: 'Ecrivez votre message...',
        chat_open: 'Ouvrir le chat',
        chat_close: 'Fermer le chat',
        chat_thinking: 'Ecriture...',
        chat_error: "Desole, une erreur s'est produite.",
        dashboard_title: 'Tableau de bord',
        dashboard_subtitle: 'Bon retour, Trader !',
        dashboard_start_trading: 'Commencer à trader',
        dashboard_account_balance: 'Solde du compte',
        dashboard_equity: 'Équité',
        dashboard_total_profit: 'Profit total',
        dashboard_daily_drawdown: 'Drawdown quotidien',
        dashboard_challenge_progress: 'Progression du challenge',
        dashboard_profit_target_progress: 'Progression de l’objectif',
        dashboard_live_hub: 'Marchés en direct - Afrique & Global',
        dashboard_ai_banner: "L'assistant IA vient de publier de nouveaux signaux",
        dashboard_ai_signals: "Signaux de trading IA",
        dashboard_ai_loading: 'Analyse des marchés...',
        dashboard_ai_empty: 'Aucun signal clair détecté.',
        dashboard_view_all_signals: 'Voir tous les signaux',
        dashboard_confidence: 'Confiance :',
        dashboard_onboarding: 'Onboarding',
        dashboard_onboarding_title: 'Checklist de démarrage',
        dashboard_onboarding_step_profile: 'Vérifier les informations du compte',
        dashboard_onboarding_step_plan: 'Choisir la taille du challenge',
        dashboard_onboarding_step_trade: 'Passer le premier trade',
        dashboard_onboarding_cta: 'Compléter le profil',
        dashboard_checklist_title: 'Suivi de progression',
        dashboard_checklist_hint: 'Termine ces étapes pour débloquer le funding et les données live.',
        dashboard_checklist_profile: 'Vérifier profil & documents',
        dashboard_checklist_challenge: 'Choisir un challenge',
        dashboard_checklist_trade: 'Passer un trade live',
        dashboard_checklist_status_completed: 'Terminé',
        dashboard_checklist_status_pending: 'En attente',
        dashboard_reco_title: 'Recommandations',
        dashboard_reco_subtitle: 'Actions prioritaires pour votre compte',
        dashboard_reco_hint: 'Mis à jour',
        dashboard_reco_funded_title: 'Débloquer les fonctions financées',
        dashboard_reco_funded_desc: 'Accédez aux données live, retraits et signaux IA.',
        dashboard_reco_funded_action: 'Mettre à niveau',
        dashboard_reco_signals_title: 'Signaux IA disponibles',
        dashboard_reco_signals_desc: 'Consultez les dernières opportunités rapidement.',
        dashboard_reco_signals_empty_title: 'Aucun signal pour le moment',
        dashboard_reco_signals_empty_desc: 'Vérifiez les marchés en direct plus tard.',
        dashboard_reco_signals_action: 'Voir les signaux',
        dashboard_reco_watchlist_title: 'Affiner votre watchlist',
        dashboard_reco_watchlist_desc: 'Suivez vos actifs les plus tradés.',
        dashboard_reco_watchlist_action: 'Ouvrir trading',
        dashboard_reco_rules_title: 'Relire les règles du challenge',
        dashboard_reco_rules_desc: 'Respectez les limites de drawdown et de temps.',
        dashboard_reco_rules_action: 'Voir les règles',
        dashboard_news_title: 'Actus Marché',
        dashboard_news_subtitle: 'Dernières infos macro et actions',
        dashboard_news_hint: 'Flux live',
        dashboard_news_empty: 'Aucune actualité disponible.',
        dashboard_news_source: 'Source :',
        dashboard_market_pulse: 'Pouls du marché',
        dashboard_market_pulse_subtitle: 'Instantanés de tendance liés aux prix en direct',
        dashboard_market_pulse_window: '28 dernières séances',
        dashboard_market_no_chart: 'Aucune donnée de graphique pour le moment',
        dashboard_market_trend: 'Tendance 28J',
        funded_only_title: 'Réservé aux financés',
        funded_only_desc: 'Passez à un compte financé pour accéder aux données live.',
        funded_only_ai: "Les signaux IA sont réservés aux comptes financés.",
        funded_only_charts: "Les graphiques TradingView sont réservés aux comptes financés.",
        funded_only_live_data: "Les données live sont réservées aux comptes financés.",
        funded_only_badge: 'Financé uniquement',
        profile_title: 'Paramètres du profil',
        profile_subtitle: 'Gérez votre compte et vos préférences',
        profile_photo: 'Photo de profil',
        profile_upload_photo: 'Importer une photo',
        profile_remove_photo: 'Supprimer la photo',
        profile_remove_photo_confirm: 'Supprimer votre photo de profil ?',
        profile_personal_info: 'Informations personnelles',
        profile_full_name: 'Nom complet',
        profile_email: 'Adresse e-mail',
        profile_phone: 'Téléphone',
        profile_country: 'Pays',
        profile_save_changes: 'Enregistrer',
        profile_change_password: 'Changer le mot de passe',
        profile_current_password: 'Mot de passe actuel',
        profile_new_password: 'Nouveau mot de passe',
        profile_confirm_password: 'Confirmer le mot de passe',
        profile_update_password: 'Mettre à jour',
        profile_preferences: 'Préférences',
        profile_language: 'Langue',
        profile_dark_mode: 'Mode sombre',
        profile_dark_mode_desc: 'Utiliser le thème de la plateforme',
        profile_danger_zone: 'Zone de danger',
        profile_delete_account: 'Supprimer le compte',
        profile_delete_warning: 'Une fois votre compte supprimé, il est impossible de revenir en arrière.',
        profile_delete_confirm: 'Supprimer définitivement votre compte ? Cette action est irréversible.',
        wallet_title: 'Portefeuille & Wallet',
        wallet_subtitle: 'Suivez les positions, le PnL et les paiements',
        wallet_balance: 'Solde',
        wallet_equity: 'Équité',
        wallet_open_positions: 'Positions ouvertes',
        wallet_asset: 'Actif',
        wallet_qty: 'Qté',
        wallet_avg_entry: 'Prix moyen',
        wallet_last: 'Dernier',
        wallet_pnl: 'PnL',
        wallet_action: 'Action',
        wallet_close: 'Clôturer',
        wallet_closing: 'Clôture...',
        wallet_no_positions: 'Aucune position ouverte.',
        wallet_allocation: 'Allocation du portefeuille',
        wallet_total: 'Total',
        wallet_allocation_empty: 'Aucune donnée d’allocation.',
        wallet_trade_history: 'Historique des trades',
        wallet_trade_empty: 'Aucun trade pour le moment.',
        wallet_side: 'Sens',
        wallet_price: 'Prix',
        wallet_challenge: 'Challenge',
        wallet_started: 'Démarré',
        wallet_days_remaining: 'jours restants',
        wallet_upgrade_plan: 'Améliorer le plan',
        wallet_available_plans: 'Plans disponibles',
        wallet_popular: 'Populaire',
        wallet_account: 'compte',
        wallet_current_plan_label: 'Plan actuel',
        wallet_select_plan: 'Choisir le plan',
        wallet_payment_history: 'Historique des paiements',
        wallet_export: 'Exporter',
        wallet_transaction: 'Transaction',
        wallet_date: 'Date',
        wallet_method: 'Méthode',
        wallet_amount: 'Montant',
        wallet_status: 'Statut',
        wallet_payment_empty: 'Aucun paiement pour le moment.',
        wallet_complete_payment: 'Finaliser le paiement',
        wallet_payment_desc: 'Vous serez redirigé vers PayPal pour finaliser le paiement.',
        wallet_selected_plan: 'Plan sélectionné',
        wallet_cancel: 'Annuler',
        wallet_pay_paypal: 'Payer avec PayPal',
        wallet_withdraw_title: 'Retraits',
        wallet_withdraw_subtitle: 'Demandez un retrait depuis vos profits financés.',
        wallet_withdraw_available: 'Profit disponible',
        wallet_withdraw_min_profit: 'Profit minimum requis',
        wallet_withdraw_status: 'Statut',
        wallet_withdraw_status_ready: 'Éligible',
        wallet_withdraw_status_locked: 'Bloqué',
        wallet_withdraw_amount: 'Montant du retrait',
        wallet_withdraw_request: 'Demander un retrait',
        wallet_withdraw_processing: 'Traitement...',
        wallet_withdraw_not_eligible: 'Les retraits sont disponibles après un profit de',
        wallet_withdraw_requested: 'Retrait demandé',
        wallet_withdraw_requested_desc: 'Votre demande a été soumise.',
        challenge_title: 'Progression du challenge',
        trading_title: 'Terminal de trading',
        trading_subtitle: 'Marchés africains & mondiaux en temps réel',
        trading_watchlist: 'Watchlist marché',
        trading_watchlist_subtitle: 'Recherchez, filtrez et suivez les prix en direct.',
        trading_hide_companies: 'Masquer les entreprises',
        trading_show_companies: 'Afficher les entreprises',
        trading_companies_hidden: 'Liste des entreprises masquée.',
        trading_assets: 'Actifs',
        trading_live: 'En direct',
        trading_search: 'Rechercher un symbole ou une entreprise...',
        trading_sort_price: 'Tri : Prix',
        trading_sort_volume: 'Tri : Volume',
        trading_sort_change: 'Tri : % Variation',
        trading_sort_desc: 'Desc',
        trading_sort_asc: 'Asc',
        trading_filter_all: 'Tous',
        trading_filter_gainers: 'Gagnants',
        trading_filter_losers: 'Perdants',
        trading_filter_volume: 'Gros volume',
        trading_execution: 'Exécution des trades',
        trading_buy: 'ACHAT',
        trading_sell: 'VENTE',
        trading_quantity: 'Quantité',
        trading_quantity_lots: 'Quantité (Lots)',
        trading_quantity_shares: 'Quantité (Actions)',
        trading_market_price: 'Prix du marché',
        trading_asset_type: 'Type d’actif',
        trading_side: 'Sens',
        trading_qty: 'Qté',
        trading_qty_lots: 'Lots',
        trading_qty_shares: 'Actions',
        trading_notional: 'Notionnel',
        trading_est: 'Estim. 1%',
        trading_execute: 'Exécuter',
        trading_ai_hub: 'Hub de prédiction TradeSense AI',
        trading_unit_lot: 'lot',
        trading_unit_lots: 'lots',
        trading_unit_shares: 'actions',
        trading_unit_units: 'unités',
        trading_unit_coins: 'coins',
        trading_tp_sl: 'Take Profit / Stop Loss',
        trading_take_profit: 'Take Profit',
        trading_stop_loss: 'Stop Loss',
        trading_tp_mode_percent: 'Mode %',
        trading_tp_mode_price: 'Mode prix',
        trading_tp_price: 'TP à',
        trading_sl_price: 'SL à',
        trading_view_mode: 'Mode',
        trading_view_simple: 'Simple',
        trading_view_pro: 'Pro',
        trading_tab_chart: 'Graphique',
        trading_tab_trade: 'Trade',
        trading_tab_watchlist: 'Watchlist',
        trading_market_all: 'Tous',
        trading_market_crypto: 'Crypto',
        trading_market_forex: 'Forex',
        trading_market_nasdaq: 'Nasdaq',
        trading_market_bvc: 'Bourse de Casablanca',
        trading_price: 'Prix',
        trading_change: 'Variation',
        trading_volume: 'Volume',
        trading_risk: 'RISQUE',
        trading_risk_tooltip: 'Risque basé sur les seuils de drawdown',
        trading_live_data: 'DONNÉES LIVE',
        trading_rules_notice: '⚠️ En exécutant, vous acceptez les règles : 5% drawdown quotidien / 10% global.',
        trading_risk_low: 'Faible',
        trading_risk_medium: 'Moyen',
        trading_risk_high: 'Élevé',
        trading_vol: 'Vol',
        trading_live_news: 'Actualités en direct',
        trading_loading_news: 'Chargement des actualités...',
        challenge_demo_type: 'Compte démo',
        challenge_trial_type: 'Essai gratuit',
        challenge_paid_type: 'Challenge Pro',
        challenge_subtitle: 'Suivez la progression de votre challenge de trading',
        challenge_demo_active: 'Mode démo actif',
        challenge_trial_active: 'Mode essai gratuit',
        challenge_demo_desc: 'Ceci est un compte démo pour pratiquer. Vous ne pouvez pas être financé.',
        challenge_trial_desc: 'Essai gratuit pour tester les règles. Passez à un challenge payant pour être financé.',
        challenge_upgrade: 'Passer au challenge payant',
        challenge_starting_balance: 'Solde initial',
        challenge_current_equity: 'Équité actuelle',
        challenge_profit_loss: 'Profit/Perte',
        challenge_limit: 'Limite :',
        challenge_approaching_limit: 'Limite proche',
        challenge_rules_title: 'Règles de trading',
        challenge_status_title: 'Guide des statuts',
        challenge_status_active: 'Le challenge est en cours. Tradez prudemment et respectez les règles.',
        challenge_status_passed: 'Bravo ! Vous avez réussi et êtes prêt à être financé.',
        challenge_status_failed: 'Challenge échoué suite à une violation. Vous pouvez recommencer.',
        challenge_rule_profit_target: 'Objectif de profit',
        challenge_rule_none: 'Aucun',
        challenge_rule_profit_desc: 'Atteignez l’objectif pour réussir',
        challenge_rule_profit_demo: 'Aucun objectif en mode démo',
        challenge_rule_daily_drawdown: 'Drawdown quotidien',
        challenge_rule_daily_desc: 'Perte maximale autorisée en une journée',
        challenge_rule_total_drawdown: 'Drawdown total',
        challenge_rule_total_desc: 'Perte maximale depuis le pic',
        challenge_rule_time_remaining: 'Temps restant',
        challenge_rule_time_desc: 'Terminer dans le temps imparti',
        challenge_days: 'jours',
        challenge_left: 'restants',
        challenge_rule_news: 'Pas de trading pendant les news à fort impact',
        challenge_rule_risk: 'Risque maximum 3% par trade',
        challenge_rule_sl: 'Stop-loss obligatoire sur toutes les positions',
        challenge_rule_weekend: 'Conserver le week-end est autorisé',
        challenge_rule_days: 'Minimum 5 jours de trading requis',
        challenge_rule_bot: 'Pas d’EA/Bot sans approbation',
        hero_badge: 'Prop firm africaine avec accès BVC',
        hero_cta_text: 'Commencer le challenge',
        hero_cta_tagline: 'Défi financé en 3 étapes : onboarding, règles, puis trading avec notre capital.',
        hero_trust_badge: 'Prop firm accréditée BVC',
        hero_trust_subtext: 'Données de la Bourse de Casablanca, monitoring IA 24/7, et 2 500+ traders africains.',
        hero_title_line1: 'Trade Smarter.',
        hero_title_line2: 'Get Funded.',
        hero_subtitle: 'Join the next generation prop trading platform. AI signals, real-time charts, professional tools. Pass the challenge and trade with our capital.',
        hero_view_plans: 'Voir les offres',
        hero_stat_capital: 'Capital financé',
        hero_stat_traders: 'Traders actifs',
        hero_stat_success: 'Taux de réussite',
        hero_stat_risk: 'Suivi du risque',
        trust_stat_traders: 'Traders financés',
        trust_stat_payout: 'Paiement moyen',
        trust_stat_winrate: 'Taux de gain hebdo',
        trust_stat_markets: 'Marchés couverts',
        trust_stat_markets_value: 'BVC + Global',
        pillars_label: 'Modèle de plateforme',
        pillars_title: 'Construit sur trois piliers',
        pillars_subtitle: 'Une structure claire pour rester discipliné et performant.',
        pillars_trade_title: 'Trade',
        pillars_trade_desc: 'Exécution multi-actifs avec BVC, FX, crypto et Nasdaq.',
        pillars_risk_title: 'Risque',
        pillars_risk_desc: 'Règles automatiques, limites de drawdown et score de risque.',
        pillars_learn_title: 'Apprendre',
        pillars_learn_desc: 'Éducation guidée, résumés IA et playbooks.',
        bvc_title: 'Marché local, outils professionnels',
        bvc_subtitle: 'Suivez les actions marocaines en temps réel avec le même flux d’exécution.',
        bvc_section_title: 'Bourse de Casablanca',
        bvc_cta_primary: 'Explorer la BVC',
        bvc_cta_secondary: 'Voir les meilleurs traders BVC',
        bvc_card_shares: 'Trading actions',
        bvc_card_shares_desc: 'Achat/vente en actions (min 1)',
        bvc_card_tv: 'Graphiques TradingView',
        bvc_card_tv_desc: 'Symboles CSEMA et données live',
        bvc_card_risk: 'Alignement du risque',
        bvc_card_risk_desc: 'Mêmes règles de challenge',
        testimonials_title: 'Recommandé par les traders',
        testimonials_subtitle: 'Rejoignez des milliers de traders disciplinés qui bâtissent des résultats réguliers.',
        testimonial_ahmed_role: 'Trader financé • Casablanca',
        testimonial_ahmed_content: 'Règles claires, exécution rapide et limites fiables. J’ai réussi en 3 semaines.',
        testimonial_sarah_role: 'Trader Pro • Rabat',
        testimonial_sarah_content: 'Le dashboard de risque m’aide à rester disciplinée. La plateforme est pro.',
        testimonial_youssef_role: 'Trader Elite • Marrakech',
        testimonial_youssef_content: 'Watchlist BVC et graphiques TradingView: tout est dans un seul terminal.',
        trader_stories_title: 'Récits de traders',
        trader_stories_subtitle: 'Des traders financés racontent comment TradeSense AI les garde disciplinés et rentables.',
        story_lina_role: 'Rabat · Trader financé',
        story_lina_quote: 'Des règles claires, un financement fiable et des signaux IA m’ont permis de rester sereine et de trader plus gros en 3 semaines.',
        story_omar_role: 'Casablanca · Analyste risque',
        story_omar_quote: 'La surveillance des risques ressemble à un deuxième regard — parfait pour respecter les contraintes à chaque trade.',
        story_samira_role: 'Dubaï · Trader croissance',
        story_samira_quote: 'Passer à un compte à 50k$ a été fluide. Le tableau de bord et les flux Casablanca me gardent à l’avance.',
        pricing_meta_duration: 'Durée du challenge',
        pricing_meta_target: 'Objectif de profit',
        pricing_meta_rules: 'Règles de drawdown',
        checkout_order_summary: 'Résumé de commande',
        checkout_payment_options: 'Options de paiement',
        checkout_total: 'Total',
        checkout_pay_now: 'Payer maintenant',
        checkout_title: 'Paiement',
        checkout_subtitle: 'Finalisez le paiement de votre challenge',
        checkout_plan_label: 'Offre',
        checkout_account_size_label: 'Taille du compte',
        checkout_price_label: 'Prix',
        checkout_loading: 'Chargement du challenge...',
        checkout_paypal_label: 'PayPal',
        checkout_paypal_connected: 'Connecté',
        checkout_paypal_not_configured: 'Non configuré',
        checkout_paypal_loading: 'Chargement PayPal...',
        checkout_paypal_missing: 'PayPal non configuré dans l’admin',
        checkout_cmi_loading: 'Chargement du portail...',
        checkout_cmi_button: 'Payer par carte bancaire (CMI)',
        checkout_crypto_loading: 'Création de commande...',
        checkout_crypto_button: 'Payer avec Binance Pay',
        admin_title: 'Centre de contrôle admin',
        admin_subtitle: 'Gérer les challenges et les statuts utilisateurs',
        admin_accounts: 'Gestion des comptes',
        admin_user_details: 'Détails utilisateur',
        admin_logs: "Journaux d'administration",
        admin_paypal_config: 'Configuration PayPal',
        admin_cmi_config: 'Configuration CMI',
        admin_crypto_config: 'Configuration Binance Pay',
        admin_action_logs: "Journaux d'administration",
        admin_account_management: 'Gestion des comptes',
        admin_total_accounts: 'Comptes totaux',
        admin_active_challenges: 'Challenges actifs',
        admin_funded: 'Financés',
        admin_failed: 'Échoués',
        admin_error: 'Erreur',
        admin_saved: 'Enregistré',
        admin_config_updated: 'Configuration mise à jour',
        admin_fetch_accounts_error: 'Impossible de charger les comptes',
        admin_fetch_details_error: 'Impossible de charger les détails',
        admin_paypal_save_error: 'Échec de sauvegarde PayPal',
        admin_cmi_save_error: 'Échec de sauvegarde CMI',
        admin_crypto_save_error: 'Échec de sauvegarde Binance Pay',
        admin_status_updated: 'Statut mis à jour',
        admin_status_updated_desc: 'Compte #{id} défini sur {status}',
        admin_status_update_error: 'Échec de mise à jour du statut',
        admin_search_accounts: 'Rechercher des comptes...',
        admin_user: 'Utilisateur',
        admin_challenge: 'Challenge',
        admin_balance: 'Solde',
        admin_status: 'Statut',
        admin_actions: 'Actions',
        admin_fund_user: 'Financer',
        admin_fail_user: 'Échouer',
        admin_reset_active: 'Réactiver',
        admin_loading: 'Chargement...',
        admin_select_account: 'Sélectionnez un compte pour afficher les détails.',
        admin_quick_actions: 'Actions rapides',
        admin_fund: 'Financer',
        admin_fail: 'Échouer',
        admin_reset: 'Réinitialiser',
        admin_open_positions: 'Positions ouvertes',
        admin_qty: 'Qté',
        admin_avg: 'Moy.',
        admin_no_positions: 'Aucune position ouverte.',
        admin_recent_trades: 'Trades récents',
        admin_no_trades: 'Aucun trade récent.',
        admin_equity: 'Équité',
        admin_paypal_client_id: 'Client ID',
        admin_paypal_client_id_placeholder: 'Identifiant PayPal',
        admin_paypal_client_secret: 'Client Secret',
        admin_paypal_client_secret_placeholder: 'Secret PayPal',
        admin_mode: 'Mode',
        admin_currency: 'Devise',
        admin_currency_placeholder: 'USD',
        admin_save_paypal: 'Enregistrer PayPal',
        admin_cmi_store_id: 'Store ID',
        admin_cmi_store_id_placeholder: 'Identifiant CMI',
        admin_cmi_shared_secret: 'Secret partagé',
        admin_cmi_shared_secret_placeholder: 'Secret CMI',
        admin_save_cmi: 'Enregistrer CMI',
        admin_crypto_api_key: 'Clé API',
        admin_crypto_api_key_placeholder: 'Clé API Binance Pay',
        admin_crypto_api_secret: 'Secret API',
        admin_crypto_api_secret_placeholder: 'Secret Binance Pay',
        admin_crypto_merchant_id: 'Merchant ID (optionnel)',
        admin_crypto_merchant_id_placeholder: 'Merchant ID',
        admin_save_crypto: 'Enregistrer Binance Pay',
        admin_no_logs: 'Aucun journal.',
        admin_payments: 'Paiements',
        admin_refresh_data: 'Rafraîchir les données',
        admin_manage_payments: 'Gérer les paiements',
        admin_manage_accounts: 'Gérer les comptes',
        admin_quick_actions_hint: 'Utilisez les actions rapides pour accéder aux tâches critiques.',
        admin_recent_logs: 'Journaux récents',
        admin_view_all_logs: 'Voir tous les journaux',
        admin_user_profile: 'Profil utilisateur',
        admin_user_name: "Nom d'utilisateur",
        admin_user_email: 'Email utilisateur',
        admin_save_user: "Enregistrer l'utilisateur",
        admin_user_updated: 'Utilisateur mis à jour',
        admin_user_update_error: "Échec de mise à jour de l'utilisateur",
        admin_account_settings: 'Paramètres du compte',
        admin_save_account: 'Enregistrer le compte',
        admin_account_updated: 'Compte mis à jour',
        admin_account_update_error: 'Échec de mise à jour du compte',
        admin_security: 'Sécurité',
        admin_new_password: 'Nouveau mot de passe',
        admin_reset_password: 'Réinitialiser le mot de passe',
        admin_password_reset: 'Mot de passe réinitialisé',
        admin_password_reset_error: 'Échec de réinitialisation du mot de passe',
        admin_delete_account: 'Supprimer le compte',
        admin_delete_account_confirm: 'Supprimer ce compte ? Action irréversible.',
        admin_account_deleted: 'Compte supprimé',
        admin_account_deleted_desc: 'Le compte a été supprimé.',
        admin_account_delete_error: 'Échec de suppression du compte',
        admin_initial_balance: 'Solde initial',
        admin_daily_starting_equity: 'Équité de départ quotidienne',
    },
    ar: {
        welcome: 'مرحبًا بك في TradeSense AI',
        hero_title: 'أول شركة تداول ممولة مدعومة بالذكاء الاصطناعي في إفريقيا',
        hero_subtitle: 'انضم إلى جيل التداول القادم. احصل على التمويل وتداول برأسمالنا.',
        start_challenge: 'ابدأ التحدي',
        dashboard: 'لوحة التحكم',
        trading: 'التداول',
        leaderboard: 'المتصدرين',
        pricing: 'الأسعار',
        contact: 'اتصل بنا',
        admin: 'المسؤول',
        login: 'تسجيل الدخول',
        register: 'التسجيل',
        nav_dashboard: 'لوحة التحكم',
        nav_trading: 'التداول',
        nav_challenge: 'التحدي',
        nav_leaderboard: 'المتصدرين',
        nav_wallet: 'المحفظة',
        nav_profile: 'الملف الشخصي',
        nav_logout: 'تسجيل الخروج',
        nav_admin: 'الإدارة',
        theme_light: 'فاتح',
        theme_dark: 'داكن',
        language: 'اللغة',
        chat_title: 'مساعد TradeSense',
        chat_subtitle: 'اسالنا اي شيء',
        chat_placeholder: 'اكتب رسالتك...',
        chat_open: 'افتح الدردشة',
        chat_close: 'اغلق الدردشة',
        chat_thinking: 'يكتب...',
        chat_error: 'حدث خطا ما.',
        dashboard_title: 'لوحة التحكم',
        dashboard_subtitle: 'مرحبًا بعودتك أيها المتداول!',
        dashboard_start_trading: 'ابدأ التداول',
        dashboard_account_balance: 'رصيد الحساب',
        dashboard_equity: 'القيمة',
        dashboard_total_profit: 'إجمالي الربح',
        dashboard_daily_drawdown: 'التراجع اليومي',
        dashboard_challenge_progress: 'تقدم التحدي',
        dashboard_profit_target_progress: 'تقدم الهدف',
        dashboard_live_hub: 'الأسواق المباشرة - إفريقيا والعالم',
        dashboard_ai_banner: 'نشر المساعد الذكي إشارات جديدة',
        dashboard_ai_signals: 'إشارات تداول بالذكاء الاصطناعي',
        dashboard_ai_loading: 'جارٍ تحليل الأسواق...',
        dashboard_ai_empty: 'لا توجد إشارات واضحة.',
        dashboard_view_all_signals: 'عرض كل الإشارات',
        dashboard_confidence: 'الثقة:',
        dashboard_onboarding: 'الإعداد',
        dashboard_onboarding_title: 'قائمة البدء',
        dashboard_onboarding_step_profile: 'تحقق من معلومات الحساب',
        dashboard_onboarding_step_plan: 'اختر حجم التحدي',
        dashboard_onboarding_step_trade: 'نفذ أول صفقة',
        dashboard_onboarding_cta: 'أكمل الملف الشخصي',
        dashboard_checklist_title: 'قائمة التقدم',
        dashboard_checklist_hint: 'أكمل هذه الخطوات لفتح التمويل وبيانات السوق الحية.',
        dashboard_checklist_profile: 'تحقق من الحساب والوثائق',
        dashboard_checklist_challenge: 'اختر تحديك',
        dashboard_checklist_trade: 'نفذ أول صفقة حية',
        dashboard_checklist_status_completed: 'مكتمل',
        dashboard_checklist_status_pending: 'قيد الانتظار',
        dashboard_reco_title: 'توصيات',
        dashboard_reco_subtitle: 'أفضل الخطوات التالية لحسابك',
        dashboard_reco_hint: 'محدّث الآن',
        dashboard_reco_funded_title: 'افتح مزايا الحساب المموّل',
        dashboard_reco_funded_desc: 'احصل على بيانات حية، السحب، وإشارات الذكاء الاصطناعي.',
        dashboard_reco_funded_action: 'ترقية الآن',
        dashboard_reco_signals_title: 'إشارات الذكاء الاصطناعي جاهزة',
        dashboard_reco_signals_desc: 'راجع أحدث الفرص وتصرف بسرعة.',
        dashboard_reco_signals_empty_title: 'لا توجد إشارات بعد',
        dashboard_reco_signals_empty_desc: 'تحقق من الأسواق لاحقًا.',
        dashboard_reco_signals_action: 'عرض الإشارات',
        dashboard_reco_watchlist_title: 'كوّن قائمة مراقبة',
        dashboard_reco_watchlist_desc: 'تابع الأصول التي تتداولها كثيرًا.',
        dashboard_reco_watchlist_action: 'فتح التداول',
        dashboard_reco_rules_title: 'راجع قواعد التحدي',
        dashboard_reco_rules_desc: 'التزم بحدود السحب والوقت.',
        dashboard_reco_rules_action: 'عرض القواعد',
        dashboard_news_title: 'عناوين السوق',
        dashboard_news_subtitle: 'آخر أخبار الاقتصاد والأسهم',
        dashboard_news_hint: 'تحديث مباشر',
        dashboard_news_empty: 'لا توجد أخبار متاحة.',
        dashboard_news_source: 'المصدر:',
        dashboard_market_pulse: 'نبض السوق',
        dashboard_market_pulse_subtitle: 'لمحات اتجاه مرتبطة بالأسعار الحية',
        dashboard_market_pulse_window: 'آخر 28 جلسة',
        dashboard_market_no_chart: 'لا توجد بيانات للرسم بعد',
        dashboard_market_trend: 'اتجاه 28 يومًا',
        funded_only_title: 'للممولين فقط',
        funded_only_desc: 'قم بالترقية إلى حساب ممول للوصول إلى بيانات السوق الحية.',
        funded_only_ai: 'إشارات الذكاء الاصطناعي متاحة للحسابات الممولة فقط.',
        funded_only_charts: 'مخططات TradingView متاحة للحسابات الممولة فقط.',
        funded_only_live_data: 'بيانات السوق الحية متاحة للحسابات الممولة فقط.',
        funded_only_badge: 'ممولة فقط',
        profile_title: 'إعدادات الملف الشخصي',
        profile_subtitle: 'إدارة الحساب والتفضيلات',
        profile_photo: 'صورة الملف الشخصي',
        profile_upload_photo: 'رفع صورة',
        profile_remove_photo: 'حذف الصورة',
        profile_remove_photo_confirm: 'حذف صورة الملف الشخصي؟',
        profile_personal_info: 'المعلومات الشخصية',
        profile_full_name: 'الاسم الكامل',
        profile_email: 'البريد الإلكتروني',
        profile_phone: 'رقم الهاتف',
        profile_country: 'الدولة',
        profile_save_changes: 'حفظ التغييرات',
        profile_change_password: 'تغيير كلمة المرور',
        profile_current_password: 'كلمة المرور الحالية',
        profile_new_password: 'كلمة المرور الجديدة',
        profile_confirm_password: 'تأكيد كلمة المرور',
        profile_update_password: 'تحديث كلمة المرور',
        profile_preferences: 'التفضيلات',
        profile_language: 'اللغة',
        profile_dark_mode: 'الوضع الداكن',
        profile_dark_mode_desc: 'استخدام السمة عبر المنصة',
        profile_danger_zone: 'منطقة الخطر',
        profile_delete_account: 'حذف الحساب',
        profile_delete_warning: 'بمجرد حذف حسابك لا يمكن التراجع عن ذلك.',
        profile_delete_confirm: 'حذف حسابك نهائيًا؟ لا يمكن التراجع عن ذلك.',
        wallet_title: 'المحفظة',
        wallet_subtitle: 'تتبّع المراكز والأرباح والمدفوعات',
        wallet_balance: 'الرصيد',
        wallet_equity: 'القيمة',
        wallet_open_positions: 'المراكز المفتوحة',
        wallet_asset: 'الأصل',
        wallet_qty: 'الكمية',
        wallet_avg_entry: 'متوسط الدخول',
        wallet_last: 'السعر الأخير',
        wallet_pnl: 'الأرباح',
        wallet_action: 'إجراء',
        wallet_close: 'إغلاق',
        wallet_closing: 'جارٍ الإغلاق...',
        wallet_no_positions: 'لا توجد مراكز مفتوحة.',
        wallet_allocation: 'توزيع المحفظة',
        wallet_total: 'الإجمالي',
        wallet_allocation_empty: 'لا توجد بيانات للتوزيع.',
        wallet_trade_history: 'سجل الصفقات',
        wallet_trade_empty: 'لا توجد صفقات بعد.',
        wallet_side: 'الاتجاه',
        wallet_price: 'السعر',
        wallet_challenge: 'تحدي',
        wallet_started: 'بدأ في',
        wallet_days_remaining: 'يومًا متبقيًا',
        wallet_upgrade_plan: 'ترقية الخطة',
        wallet_available_plans: 'الخطط المتاحة',
        wallet_popular: 'الأكثر شعبية',
        wallet_account: 'حساب',
        wallet_current_plan_label: 'الخطة الحالية',
        wallet_select_plan: 'اختيار الخطة',
        wallet_payment_history: 'سجل المدفوعات',
        wallet_export: 'تصدير',
        wallet_transaction: 'المعاملة',
        wallet_date: 'التاريخ',
        wallet_method: 'الطريقة',
        wallet_amount: 'المبلغ',
        wallet_status: 'الحالة',
        wallet_payment_empty: 'لا توجد مدفوعات بعد.',
        wallet_complete_payment: 'إتمام الدفع',
        wallet_payment_desc: 'سيتم تحويلك إلى بايبال لإتمام الدفع بأمان.',
        wallet_selected_plan: 'الخطة المختارة',
        wallet_cancel: 'إلغاء',
        wallet_pay_paypal: 'الدفع عبر بايبال',
        wallet_withdraw_title: 'السحوبات',
        wallet_withdraw_subtitle: 'اطلب سحبًا من أرباح حسابك الممول.',
        wallet_withdraw_available: 'الربح المتاح',
        wallet_withdraw_min_profit: 'الحد الأدنى للربح',
        wallet_withdraw_status: 'الحالة',
        wallet_withdraw_status_ready: 'مؤهل',
        wallet_withdraw_status_locked: 'مقفل',
        wallet_withdraw_amount: 'مبلغ السحب',
        wallet_withdraw_request: 'طلب سحب',
        wallet_withdraw_processing: 'جارٍ المعالجة...',
        wallet_withdraw_not_eligible: 'السحوبات متاحة بعد تحقيق ربح قدره',
        wallet_withdraw_requested: 'تم طلب السحب',
        wallet_withdraw_requested_desc: 'تم إرسال طلبك.',
        challenge_title: 'تقدم التحدي',
        trading_title: 'منصة التداول',
        trading_subtitle: 'أسواق إفريقيا والعالم في الوقت الحقيقي',
        trading_watchlist: 'قائمة المتابعة',
        trading_watchlist_subtitle: 'ابحث وفلتر وتابع الأسعار المباشرة.',
        trading_hide_companies: 'إخفاء الشركات',
        trading_show_companies: 'إظهار الشركات',
        trading_companies_hidden: 'قائمة الشركات مخفية.',
        trading_assets: 'الأصول',
        trading_live: 'مباشر',
        trading_search: 'ابحث عن رمز أو شركة...',
        trading_sort_price: 'فرز: السعر',
        trading_sort_volume: 'فرز: الحجم',
        trading_sort_change: 'فرز: نسبة التغير',
        trading_sort_desc: 'تنازلي',
        trading_sort_asc: 'تصاعدي',
        trading_filter_all: 'الكل',
        trading_filter_gainers: 'الرابحون',
        trading_filter_losers: 'الخاسرون',
        trading_filter_volume: 'حجم مرتفع',
        trading_execution: 'تنفيذ الصفقة',
        trading_buy: 'شراء',
        trading_sell: 'بيع',
        trading_quantity: 'الكمية',
        trading_quantity_lots: 'الكمية (لوت)',
        trading_quantity_shares: 'الكمية (أسهم)',
        trading_market_price: 'سعر السوق',
        trading_asset_type: 'نوع الأصل',
        trading_side: 'الاتجاه',
        trading_qty: 'الكمية',
        trading_qty_lots: 'لوت',
        trading_qty_shares: 'أسهم',
        trading_notional: 'القيمة',
        trading_est: 'تقريبي 1%',
        trading_execute: 'تنفيذ',
        trading_ai_hub: 'مركز تنبؤ TradeSense AI',
        trading_unit_lot: 'لوت',
        trading_unit_lots: 'لوت',
        trading_unit_shares: 'أسهم',
        trading_unit_units: 'وحدات',
        trading_unit_coins: 'عملات',
        trading_tp_sl: 'جني الربح / وقف الخسارة',
        trading_take_profit: 'جني الربح',
        trading_stop_loss: 'وقف الخسارة',
        trading_tp_mode_percent: 'وضع %',
        trading_tp_mode_price: 'وضع السعر',
        trading_tp_price: 'TP عند',
        trading_sl_price: 'SL عند',
        trading_view_mode: 'الوضع',
        trading_view_simple: 'مبسط',
        trading_view_pro: 'احترافي',
        trading_tab_chart: 'الرسم',
        trading_tab_trade: 'صفقة',
        trading_tab_watchlist: 'قائمة المتابعة',
        trading_market_all: 'الكل',
        trading_market_crypto: 'العملات الرقمية',
        trading_market_forex: 'الفوركس',
        trading_market_nasdaq: 'ناسداك',
        trading_market_bvc: 'بورصة الدار البيضاء',
        trading_price: 'السعر',
        trading_change: 'التغير',
        trading_volume: 'الحجم',
        trading_risk: 'المخاطر',
        trading_risk_tooltip: 'المخاطر بناءً على حدود التراجع',
        trading_live_data: 'بيانات مباشرة',
        trading_rules_notice: '⚠️ بتنفيذ الصفقة أنت توافق على القواعد: 5% تراجع يومي / 10% إجمالي.',
        trading_risk_low: 'منخفض',
        trading_risk_medium: 'متوسط',
        trading_risk_high: 'مرتفع',
        trading_vol: 'الحجم',
        trading_live_news: 'أخبار مباشرة',
        trading_loading_news: 'جارٍ تحميل الأخبار...',
        challenge_demo_type: 'حساب تجريبي',
        challenge_trial_type: 'تجربة مجانية',
        challenge_paid_type: 'تحدي برو',
        challenge_subtitle: 'تتبّع تقدم تحدي التداول الخاص بك',
        challenge_demo_active: 'الوضع التجريبي مفعل',
        challenge_trial_active: 'وضع التجربة المجانية',
        challenge_demo_desc: 'هذا حساب تدريبي. لا يمكنك الحصول على تمويل من الحساب التجريبي.',
        challenge_trial_desc: 'تجربة مجانية لاختبار القواعد. قم بالترقية لتحدي مدفوع للحصول على التمويل.',
        challenge_upgrade: 'الترقية إلى تحدي مدفوع',
        challenge_starting_balance: 'الرصيد الابتدائي',
        challenge_current_equity: 'القيمة الحالية',
        challenge_profit_loss: 'الربح/الخسارة',
        challenge_limit: 'الحد:',
        challenge_approaching_limit: 'الاقتراب من الحد',
        challenge_rules_title: 'قواعد التداول',
        challenge_status_title: 'دليل الحالات',
        challenge_status_active: 'التحدي قيد التنفيذ. تداول بحذر واتبع القواعد.',
        challenge_status_passed: 'تهانينا! لقد نجحت وأنت جاهز للتمويل.',
        challenge_status_failed: 'فشل التحدي بسبب مخالفة القواعد. يمكنك بدء تحدٍ جديد.',
        challenge_rule_profit_target: 'هدف الربح',
        challenge_rule_none: 'لا يوجد',
        challenge_rule_profit_desc: 'حقق الهدف للنجاح',
        challenge_rule_profit_demo: 'لا يوجد هدف في الوضع التجريبي',
        challenge_rule_daily_drawdown: 'التراجع اليومي',
        challenge_rule_daily_desc: 'أقصى خسارة مسموحة في يوم واحد',
        challenge_rule_total_drawdown: 'التراجع الكلي',
        challenge_rule_total_desc: 'أقصى خسارة من القمة',
        challenge_rule_time_remaining: 'الوقت المتبقي',
        challenge_rule_time_desc: 'الإكمال ضمن الوقت المحدد',
        challenge_days: 'يوم',
        challenge_left: 'متبقي',
        challenge_rule_news: 'لا تداول أثناء الأخبار عالية التأثير',
        challenge_rule_risk: 'أقصى مخاطرة 3% لكل صفقة',
        challenge_rule_sl: 'وقف خسارة إلزامي لكل الصفقات',
        challenge_rule_weekend: 'السماح بالاحتفاظ خلال عطلة الأسبوع',
        challenge_rule_days: 'حد أدنى 5 أيام تداول',
        challenge_rule_bot: 'لا روبوتات/EA بدون موافقة',
        hero_badge: 'شركة بروب أفريقية مع وصول إلى BVC',
        hero_cta_text: 'ابدأ التحدي',
        hero_title_line1: 'Trade Smarter.',
        hero_title_line2: 'Get Funded.',
        hero_subtitle: 'Join the next generation prop trading platform. AI signals, real-time charts, professional tools. Pass the challenge and trade with our capital.',
        hero_view_plans: 'عرض الخطط',
        hero_stat_capital: 'رأس مال ممول',
        hero_stat_traders: 'متداولون نشطون',
        hero_stat_success: 'نسبة النجاح',
        hero_stat_risk: 'مراقبة المخاطر',
        trust_stat_traders: 'متداولون ممولون',
        trust_stat_payout: 'متوسط الدفع',
        trust_stat_winrate: 'نسبة الربح الأسبوعية',
        trust_stat_markets: 'الأسواق المغطاة',
        trust_stat_markets_value: 'BVC + الأسواق العالمية',
        pillars_label: 'نموذج المنصة',
        pillars_title: 'مبني على ثلاثة أعمدة',
        pillars_subtitle: 'هيكلة واضحة تساعدك على الانضباط والالتزام.',
        pillars_trade_title: 'تداول',
        pillars_trade_desc: 'تنفيذ متعدد الأصول مع BVC وFX والعملات الرقمية وناسداك.',
        pillars_risk_title: 'مخاطر',
        pillars_risk_desc: 'قواعد آلية وحدود تراجع وتقييم مخاطر فوري.',
        pillars_learn_title: 'تعلم',
        pillars_learn_desc: 'تعليم موجه وملخصات بالذكاء الاصطناعي.',
        bvc_title: 'سوق محلي بأدوات احترافية',
        bvc_subtitle: 'تابع الأسهم المغربية في الوقت الحقيقي مع نفس تدفق التنفيذ.',
        bvc_section_title: 'بورصة الدار البيضاء',
        bvc_cta_primary: 'استكشف BVC',
        bvc_cta_secondary: 'أفضل متداولي BVC',
        bvc_card_shares: 'تداول الأسهم',
        bvc_card_shares_desc: 'شراء وبيع بالأسهم (حد أدنى 1)',
        bvc_card_tv: 'رسوم TradingView',
        bvc_card_tv_desc: 'رموز CSEMA وبيانات مباشرة',
        bvc_card_risk: 'مواءمة المخاطر',
        bvc_card_risk_desc: 'نفس قواعد التحدي',
        testimonials_title: 'موثوق من قبل المتداولين',
        testimonials_subtitle: 'انضم إلى آلاف المتداولين المنضبطين الذين يبنون نتائج مستقرة.',
        testimonial_ahmed_role: 'متداول ممول • الدار البيضاء',
        testimonial_ahmed_content: 'قواعد واضحة وتنفيذ سريع وحدود مخاطر موثوقة. نجحت خلال 3 أسابيع.',
        testimonial_sarah_role: 'متداول برو • الرباط',
        testimonial_sarah_content: 'لوحة المخاطر تبقيني منضبطة. المنصة احترافية ومركزة.',
        testimonial_youssef_role: 'متداول إيليت • مراكش',
        testimonial_youssef_content: 'قائمة BVC ورسوم TradingView ميزة قوية. كل شيء في منصة واحدة.',
        trader_stories_title: 'قصص المتداولين',
        trader_stories_subtitle: 'متداولون ممولون يروون كيف تبقيهم TradeSense AI منضبطين ومربحين.',
        story_lina_role: 'الرباط · متداولة ممولة',
        story_lina_quote: 'قواعد واضحة، تمويل موثوق، وإشارات ذكية سمحت لي بالتداول بثقة أكبر خلال 3 أسابيع.',
        story_omar_role: 'الدار البيضاء · محلل المخاطر',
        story_omar_quote: 'رصد المخاطر يشبه وجود عين ثانية — مثالي للبقاء ضمن الحدود في كل صفقة.',
        story_samira_role: 'دبي · متداولة نمو',
        story_samira_quote: 'الترقية إلى حساب 50 ألف دولار كانت سلسة. لوحة القيادة وتدفقات الدار البيضاء تبقيني في الصدارة.',
        pricing_meta_duration: 'مدة التحدي',
        pricing_meta_target: 'هدف الربح',
        pricing_meta_rules: 'قواعد التراجع',
        checkout_order_summary: 'ملخص الطلب',
        checkout_payment_options: 'خيارات الدفع',
        checkout_total: 'الإجمالي',
        checkout_pay_now: 'ادفع الآن',
        checkout_title: 'الدفع',
        checkout_subtitle: 'أكمل دفع التحدي الخاص بك',
        checkout_plan_label: 'الخطة',
        checkout_account_size_label: 'حجم الحساب',
        checkout_price_label: 'السعر',
        checkout_loading: 'جارٍ تحميل التحدي...',
        checkout_paypal_label: 'بايبال',
        checkout_paypal_connected: 'متصل',
        checkout_paypal_not_configured: 'غير مهيأ',
        checkout_paypal_loading: 'جارٍ تحميل PayPal...',
        checkout_paypal_missing: 'PayPal غير مهيأ في لوحة الإدارة',
        checkout_cmi_loading: 'جارٍ تحميل البوابة...',
        checkout_cmi_button: 'ادفع بالبطاقة البنكية (CMI)',
        checkout_crypto_loading: 'جارٍ إنشاء الطلب...',
        checkout_crypto_button: 'ادفع عبر Binance Pay',
        admin_title: 'لوحة تحكم الإدارة',
        admin_subtitle: 'إدارة التحديات وحالات المستخدمين',
        admin_accounts: 'إدارة الحسابات',
        admin_user_details: 'تفاصيل المستخدم',
        admin_logs: 'سجل الإدارة',
        admin_paypal_config: 'إعدادات بايبال',
        admin_cmi_config: 'إعدادات CMI',
        admin_crypto_config: 'إعدادات Binance Pay',
        admin_action_logs: 'سجل الإدارة',
        admin_account_management: 'إدارة الحسابات',
        admin_total_accounts: 'إجمالي الحسابات',
        admin_active_challenges: 'التحديات النشطة',
        admin_funded: 'ممولة',
        admin_failed: 'فاشلة',
        admin_error: 'خطأ',
        admin_saved: 'تم الحفظ',
        admin_config_updated: 'تم تحديث الإعدادات',
        admin_fetch_accounts_error: 'فشل تحميل الحسابات',
        admin_fetch_details_error: 'فشل تحميل التفاصيل',
        admin_paypal_save_error: 'فشل حفظ إعدادات PayPal',
        admin_cmi_save_error: 'فشل حفظ إعدادات CMI',
        admin_crypto_save_error: 'فشل حفظ إعدادات Binance Pay',
        admin_status_updated: 'تم تحديث الحالة',
        admin_status_updated_desc: 'تم تحديث الحساب #{id} إلى {status}',
        admin_status_update_error: 'فشل تحديث الحالة',
        admin_search_accounts: 'ابحث عن حسابات...',
        admin_user: 'المستخدم',
        admin_challenge: 'التحدي',
        admin_balance: 'الرصيد',
        admin_status: 'الحالة',
        admin_actions: 'الإجراءات',
        admin_fund_user: 'تمويل',
        admin_fail_user: 'فشل',
        admin_reset_active: 'إعادة التفعيل',
        admin_loading: 'جارٍ التحميل...',
        admin_select_account: 'اختر حسابًا لعرض التفاصيل.',
        admin_quick_actions: 'إجراءات سريعة',
        admin_fund: 'تمويل',
        admin_fail: 'فشل',
        admin_reset: 'إعادة ضبط',
        admin_open_positions: 'المراكز المفتوحة',
        admin_qty: 'الكمية',
        admin_avg: 'المتوسط',
        admin_no_positions: 'لا توجد مراكز مفتوحة.',
        admin_recent_trades: 'الصفقات الأخيرة',
        admin_no_trades: 'لا توجد صفقات حديثة.',
        admin_equity: 'القيمة',
        admin_paypal_client_id: 'معرف العميل',
        admin_paypal_client_id_placeholder: 'معرف بايبال',
        admin_paypal_client_secret: 'السر',
        admin_paypal_client_secret_placeholder: 'سر بايبال',
        admin_mode: 'الوضع',
        admin_currency: 'العملة',
        admin_currency_placeholder: 'USD',
        admin_save_paypal: 'حفظ إعدادات بايبال',
        admin_cmi_store_id: 'معرف المتجر',
        admin_cmi_store_id_placeholder: 'معرف CMI',
        admin_cmi_shared_secret: 'السر المشترك',
        admin_cmi_shared_secret_placeholder: 'سر CMI',
        admin_save_cmi: 'حفظ إعدادات CMI',
        admin_crypto_api_key: 'مفتاح API',
        admin_crypto_api_key_placeholder: 'مفتاح Binance Pay',
        admin_crypto_api_secret: 'سر API',
        admin_crypto_api_secret_placeholder: 'سر Binance Pay',
        admin_crypto_merchant_id: 'معرف التاجر (اختياري)',
        admin_crypto_merchant_id_placeholder: 'معرف التاجر',
        admin_save_crypto: 'حفظ إعدادات Binance Pay',
        admin_no_logs: 'لا توجد سجلات.',
        admin_payments: 'المدفوعات',
        admin_refresh_data: 'تحديث البيانات',
        admin_manage_payments: 'إدارة المدفوعات',
        admin_manage_accounts: 'إدارة الحسابات',
        admin_quick_actions_hint: 'استخدم الإجراءات السريعة للوصول إلى المهام المهمة.',
        admin_recent_logs: 'السجلات الأخيرة',
        admin_view_all_logs: 'عرض جميع السجلات',
        admin_user_profile: 'ملف المستخدم',
        admin_user_name: 'اسم المستخدم',
        admin_user_email: 'بريد المستخدم',
        admin_save_user: 'حفظ المستخدم',
        admin_user_updated: 'تم تحديث المستخدم',
        admin_user_update_error: 'فشل تحديث المستخدم',
        admin_account_settings: 'إعدادات الحساب',
        admin_save_account: 'حفظ الحساب',
        admin_account_updated: 'تم تحديث الحساب',
        admin_account_update_error: 'فشل تحديث الحساب',
        admin_security: 'الأمان',
        admin_new_password: 'كلمة مرور جديدة',
        admin_reset_password: 'إعادة تعيين كلمة المرور',
        admin_password_reset: 'تمت إعادة تعيين كلمة المرور',
        admin_password_reset_error: 'فشل إعادة تعيين كلمة المرور',
        admin_delete_account: 'حذف الحساب',
        admin_delete_account_confirm: 'حذف هذا الحساب؟ لا يمكن التراجع.',
        admin_account_deleted: 'تم حذف الحساب',
        admin_account_deleted_desc: 'تمت إزالة الحساب.',
        admin_account_delete_error: 'فشل حذف الحساب',
        admin_initial_balance: 'الرصيد الابتدائي',
        admin_daily_starting_equity: 'حقوق الملكية اليومية الابتدائية',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>(() => {
        const saved = localStorage.getItem('tradesense.language') as Language | null;
        return saved || 'fr';
    });

    useEffect(() => {
        localStorage.setItem('tradesense.language', language);
    }, [language]);

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            <div dir={language === 'ar' ? 'rtl' : 'ltr'}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
